//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xena.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Files {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Files() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xena.Resources.Files", typeof(Files).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xfd:document xmlns:xfd=&quot;http://www.ecrion.com/xfd/1.0&quot; xmlns:fo=&quot;http://www.w3.org/1999/XSL/Format&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:xf=&quot;http://www.ecrion.com/xf/1.0&quot; xmlns:xc=&quot;http://www.ecrion.com/2008/xc&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot; dt-namespaces=&quot;&quot; sample-xml=&quot;.\ExampleData\Xena_Reports_DefaultXSLT_Reminder.xml&quot;&gt;
        ///	&lt;xfd:localization&gt;
        ///		&lt;xfd:locale language-id=&quot;da_DK&quot; language-name=&quot;Danish&quot;/&gt;
        ///	&lt;/xfd:localization&gt;
        ///&lt;!-- Attributes [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Report_ReminderStep_1 {
            get {
                return ResourceManager.GetString("Report_ReminderStep_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xfd:document xmlns:xfd=&quot;http://www.ecrion.com/xfd/1.0&quot; xmlns:fo=&quot;http://www.w3.org/1999/XSL/Format&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:xf=&quot;http://www.ecrion.com/xf/1.0&quot; xmlns:xc=&quot;http://www.ecrion.com/2008/xc&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot; dt-namespaces=&quot;&quot; sample-xml=&quot;.\ExampleData\Xena_Reports_DefaultXSLT_Reminder.xml&quot;&gt;
        ///	&lt;xfd:localization&gt;
        ///		&lt;xfd:locale language-id=&quot;da_DK&quot; language-name=&quot;Danish&quot;/&gt;
        ///	&lt;/xfd:localization&gt;
        ///&lt;!-- Attributes [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Report_ReminderStep_2 {
            get {
                return ResourceManager.GetString("Report_ReminderStep_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xfd:document xmlns:xfd=&quot;http://www.ecrion.com/xfd/1.0&quot; xmlns:fo=&quot;http://www.w3.org/1999/XSL/Format&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:xf=&quot;http://www.ecrion.com/xf/1.0&quot; xmlns:xc=&quot;http://www.ecrion.com/2008/xc&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot; dt-namespaces=&quot;&quot; sample-xml=&quot;.\ExampleData\Xena_Reports_DefaultXSLT_Reminder.xml&quot;&gt;
        ///	&lt;xfd:localization&gt;
        ///		&lt;xfd:locale language-id=&quot;da_DK&quot; language-name=&quot;Danish&quot;/&gt;
        ///	&lt;/xfd:localization&gt;
        ///&lt;!-- Attributes [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Report_ReminderStep_3 {
            get {
                return ResourceManager.GetString("Report_ReminderStep_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xfd:document xmlns:fo=&quot;http://www.w3.org/1999/XSL/Format&quot; xmlns:xfd=&quot;http://www.ecrion.com/xfd/1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:xf=&quot;http://www.ecrion.com/xf/1.0&quot; xmlns:xc=&quot;http://www.ecrion.com/2008/xc&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot; fo:font-family=&quot;Times&quot; fo:font-size=&quot;12pt&quot; sample-xml=&quot;.\ExampleData\Xena_Reports_DefaultXSLT_ArticlePostReportList.xml&quot;&gt;
        ///	&lt;xfd:localization&gt;
        ///		&lt;xfd:locale language-id=&quot;da_DK&quot; language-name=&quot;Danish&quot;/&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Xena_Reports_DefaultXSLT_ArticleGroupStatisticReportList {
            get {
                return ResourceManager.GetString("Xena_Reports_DefaultXSLT_ArticleGroupStatisticReportList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xfd:document xmlns:fo=&quot;http://www.w3.org/1999/XSL/Format&quot; xmlns:xfd=&quot;http://www.ecrion.com/xfd/1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:xf=&quot;http://www.ecrion.com/xf/1.0&quot; xmlns:xc=&quot;http://www.ecrion.com/2008/xc&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot; fo:font-family=&quot;Times&quot; fo:font-size=&quot;12pt&quot; sample-xml=&quot;.\ExampleData\Xena_Reports_DefaultXSLT_ArticlePostReportList.xml&quot;&gt;
        ///	&lt;xfd:localization&gt;
        ///		&lt;xfd:locale language-id=&quot;da_DK&quot; language-name=&quot;Danish&quot;/&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Xena_Reports_DefaultXSLT_ArticleMarginReportList {
            get {
                return ResourceManager.GetString("Xena_Reports_DefaultXSLT_ArticleMarginReportList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xfd:document xmlns:fo=&quot;http://www.w3.org/1999/XSL/Format&quot; xmlns:xfd=&quot;http://www.ecrion.com/xfd/1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:xf=&quot;http://www.ecrion.com/xf/1.0&quot; xmlns:xc=&quot;http://www.ecrion.com/2008/xc&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot; fo:font-family=&quot;Times&quot; fo:font-size=&quot;12pt&quot; sample-xml=&quot;.\ExampleData\Xena_Reports_DefaultXSLT_ArticlePostReportList.xml&quot;&gt;
        ///  &lt;xfd:localization&gt;
        ///    &lt;xfd:locale language-id=&quot;da_DK&quot; language-name=&quot;Danish [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Xena_Reports_DefaultXSLT_ArticlePostReportList {
            get {
                return ResourceManager.GetString("Xena_Reports_DefaultXSLT_ArticlePostReportList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xfd:document xmlns:fo=&quot;http://www.w3.org/1999/XSL/Format&quot; xmlns:xfd=&quot;http://www.ecrion.com/xfd/1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:xf=&quot;http://www.ecrion.com/xf/1.0&quot; xmlns:xc=&quot;http://www.ecrion.com/2008/xc&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot; fo:font-family=&quot;Times&quot; fo:font-size=&quot;12pt&quot; sample-xml=&quot;.\ExampleData\Xena_Reports_DefaultXSLT_ArticlePostReportList.xml&quot;&gt;
        ///  &lt;xfd:localization&gt;
        ///    &lt;xfd:locale language-id=&quot;da_DK&quot; language-name=&quot;Danish [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Xena_Reports_DefaultXSLT_ArticleStockReportList {
            get {
                return ResourceManager.GetString("Xena_Reports_DefaultXSLT_ArticleStockReportList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xfd:document xmlns:fo=&quot;http://www.w3.org/1999/XSL/Format&quot; xmlns:xfd=&quot;http://www.ecrion.com/xfd/1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:xf=&quot;http://www.ecrion.com/xf/1.0&quot; xmlns:xc=&quot;http://www.ecrion.com/2008/xc&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot; fo:font-family=&quot;Times&quot; fo:font-size=&quot;12pt&quot; sample-xml=&quot;.\ExampleData\Xena_Reports_DefaultXSLT_ArticlePostReportList.xml&quot;&gt;
        ///  &lt;xfd:localization&gt;
        ///    &lt;xfd:locale language-id=&quot;da_DK&quot; language-name=&quot;Danish [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Xena_Reports_DefaultXSLT_EUSalesVatFree {
            get {
                return ResourceManager.GetString("Xena_Reports_DefaultXSLT_EUSalesVatFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xfd:document xmlns:fo=&quot;http://www.w3.org/1999/XSL/Format&quot; xmlns:xfd=&quot;http://www.ecrion.com/xfd/1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:xf=&quot;http://www.ecrion.com/xf/1.0&quot; xmlns:xc=&quot;http://www.ecrion.com/2008/xc&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot; fo:font-family=&quot;Times&quot; fo:font-size=&quot;12pt&quot; sample-xml=&quot;.\ExampleData\Xena_Reports_DefaultXSLT_FiscalBalance.xml&quot;&gt;
        ///	&lt;xfd:localization&gt;
        ///		&lt;xfd:locale language-id=&quot;en_US&quot; language-name=&quot;English (United S [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Xena_Reports_DefaultXSLT_FiscalBalance {
            get {
                return ResourceManager.GetString("Xena_Reports_DefaultXSLT_FiscalBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xfd:document xmlns:fo=&quot;http://www.w3.org/1999/XSL/Format&quot; xmlns:xfd=&quot;http://www.ecrion.com/xfd/1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:xf=&quot;http://www.ecrion.com/xf/1.0&quot; xmlns:xc=&quot;http://www.ecrion.com/2008/xc&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot; fo:font-family=&quot;Times&quot; fo:font-size=&quot;12pt&quot; sample-xml=&quot;.\ExampleData\Xena_Reports_DefaultXSLT_FiscalBalance.xml&quot;&gt;
        ///  &lt;xfd:localization&gt;
        ///    &lt;xfd:locale language-id=&quot;da_DK&quot; language-name=&quot;Danish&quot;/&gt;
        ///  &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Xena_Reports_DefaultXSLT_FiscalBalanceAccountant {
            get {
                return ResourceManager.GetString("Xena_Reports_DefaultXSLT_FiscalBalanceAccountant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xfd:document xmlns:fo=&quot;http://www.w3.org/1999/XSL/Format&quot; xmlns:xfd=&quot;http://www.ecrion.com/xfd/1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:xf=&quot;http://www.ecrion.com/xf/1.0&quot; xmlns:xc=&quot;http://www.ecrion.com/2008/xc&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot; fo:font-family=&quot;Times&quot; fo:font-size=&quot;12pt&quot; sample-xml=&quot;.\ExampleData\Xena_Reports_DefaultXSLT_ArticlePostReportList.xml&quot;&gt;
        ///	&lt;xfd:localization&gt;
        ///		&lt;xfd:locale language-id=&quot;da_DK&quot; language-name=&quot;Danish&quot;/&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Xena_Reports_DefaultXSLT_HistoricStockValueReportList {
            get {
                return ResourceManager.GetString("Xena_Reports_DefaultXSLT_HistoricStockValueReportList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xfd:document xmlns:fo=&quot;http://www.w3.org/1999/XSL/Format&quot; xmlns:xfd=&quot;http://www.ecrion.com/xfd/1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:xf=&quot;http://www.ecrion.com/xf/1.0&quot; xmlns:xc=&quot;http://www.ecrion.com/2008/xc&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot; fo:font-family=&quot;Times&quot; fo:font-size=&quot;12pt&quot; sample-xml=&quot;.\ExampleData\Xena_Reports_DefaultXSLT_InventoryCountingList.xml&quot;&gt;
        ///  &lt;xfd:localization&gt;
        ///    &lt;xfd:locale language-id=&quot;da_DK&quot; language-name=&quot;Danish [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Xena_Reports_DefaultXSLT_InventoryCountingList {
            get {
                return ResourceManager.GetString("Xena_Reports_DefaultXSLT_InventoryCountingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xfd:document xmlns:fo=&quot;http://www.w3.org/1999/XSL/Format&quot; xmlns:xfd=&quot;http://www.ecrion.com/xfd/1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:xf=&quot;http://www.ecrion.com/xf/1.0&quot; xmlns:xc=&quot;http://www.ecrion.com/2008/xc&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot; fo:font-family=&quot;Times&quot; fo:font-size=&quot;12pt&quot; sample-xml=&quot;.\ExampleData\Xena_Reports_DefaultXSLT_LedgerAccountSpecificationReportList.xml&quot;&gt;
        ///  &lt;xfd:localization&gt;
        ///    &lt;xfd:locale language-id=&quot;da_DK&quot; langua [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Xena_Reports_DefaultXSLT_LedgerAccountSpecificationReportList {
            get {
                return ResourceManager.GetString("Xena_Reports_DefaultXSLT_LedgerAccountSpecificationReportList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xfd:document xmlns:fo=&quot;http://www.w3.org/1999/XSL/Format&quot; xmlns:xfd=&quot;http://www.ecrion.com/xfd/1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:xf=&quot;http://www.ecrion.com/xf/1.0&quot; xmlns:xc=&quot;http://www.ecrion.com/2008/xc&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot; fo:font-family=&quot;Times&quot; fo:font-size=&quot;12pt&quot; sample-xml=&quot;.\ExampleData\Xena_Reports_DefaultXSLT_FiscalBalance.xml&quot;&gt;
        ///  &lt;xfd:localization&gt;
        ///    &lt;xfd:locale language-id=&quot;da_DK&quot; language-name=&quot;Dansk&quot;/&gt;
        ///  &lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Xena_Reports_DefaultXSLT_LedgerJournal {
            get {
                return ResourceManager.GetString("Xena_Reports_DefaultXSLT_LedgerJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xfd:document xmlns:fo=&quot;http://www.w3.org/1999/XSL/Format&quot; xmlns:xfd=&quot;http://www.ecrion.com/xfd/1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:xf=&quot;http://www.ecrion.com/xf/1.0&quot; xmlns:xc=&quot;http://www.ecrion.com/2008/xc&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot; fo:font-family=&quot;Times&quot; fo:font-size=&quot;12pt&quot; sample-xml=&quot;.\ExampleData\Xena_Reports_DefaultXSLT_LedgerPostReportList.xml&quot;&gt;
        ///  &lt;xfd:localization&gt;
        ///    &lt;xfd:locale language-id=&quot;da_DK&quot; language-name=&quot;Danish&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Xena_Reports_DefaultXSLT_LedgerPostReportList {
            get {
                return ResourceManager.GetString("Xena_Reports_DefaultXSLT_LedgerPostReportList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xfd:document xmlns:fo=&quot;http://www.w3.org/1999/XSL/Format&quot; xmlns:xfd=&quot;http://www.ecrion.com/xfd/1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:xf=&quot;http://www.ecrion.com/xf/1.0&quot; xmlns:xc=&quot;http://www.ecrion.com/2008/xc&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot; fo:font-family=&quot;Times&quot; fo:font-size=&quot;12pt&quot; sample-xml=&quot;.\ExampleData\Xena_Reports_DefaultXSLT_LedgerTagStatement.xml&quot;&gt;
        ///  &lt;xfd:localization&gt;
        ///    &lt;xfd:locale language-id=&quot;da_DK&quot; language-name=&quot;Danish&quot;/&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Xena_Reports_DefaultXSLT_LedgerTagStatement {
            get {
                return ResourceManager.GetString("Xena_Reports_DefaultXSLT_LedgerTagStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xfd:document xmlns:fo=&quot;http://www.w3.org/1999/XSL/Format&quot; xmlns:xfd=&quot;http://www.ecrion.com/xfd/1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:xf=&quot;http://www.ecrion.com/xf/1.0&quot; xmlns:xc=&quot;http://www.ecrion.com/2008/xc&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot; fo:font-family=&quot;Times&quot; fo:font-size=&quot;12pt&quot; sample-xml=&quot;.\ExampleData\Xena_Reports_DefaultXSLT_ArticlePostReportList.xml&quot;&gt;
        ///	&lt;xfd:localization&gt;
        ///		&lt;xfd:locale language-id=&quot;da_DK&quot; language-name=&quot;Danish&quot;/&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Xena_Reports_DefaultXSLT_LedgerTagStatisticReportList {
            get {
                return ResourceManager.GetString("Xena_Reports_DefaultXSLT_LedgerTagStatisticReportList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;xfd:document xmlns:xfd=&quot;http://www.ecrion.com/xfd/1.0&quot; xmlns:fo=&quot;http://www.w3.org/1999/XSL/Format&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:xf=&quot;http://www.ecrion.com/xf/1.0&quot; xmlns:xc=&quot;http://www.ecrion.com/2008/xc&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot; dt-namespaces=&quot;&quot; sample-xml=&quot;.\ExampleData\Xena_Reports_DefaultXSLT_OrderConfirmation.xml&quot;&gt;
        ///  &lt;xfd:localization&gt;
        ///    &lt;xfd:locale language-id=&quot;da_DK&quot; language-name=&quot;Danish&quot;/&gt;
        ///  &lt;/xfd:localization&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Xena_Reports_DefaultXSLT_OrderConfirmation {
            get {
                return ResourceManager.GetString("Xena_Reports_DefaultXSLT_OrderConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;xfd:document xmlns:xfd=&quot;http://www.ecrion.com/xfd/1.0&quot; xmlns:fo=&quot;http://www.w3.org/1999/XSL/Format&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:xf=&quot;http://www.ecrion.com/xf/1.0&quot; xmlns:xc=&quot;http://www.ecrion.com/2008/xc&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot; dt-namespaces=&quot;&quot; sample-xml=&quot;.\ExampleData\Xena_Reports_DefaultXSLT_OrderDelivery.xml&quot;&gt;
        ///  &lt;xfd:localization&gt;
        ///    &lt;xfd:locale language-id=&quot;da_DK&quot; language-name=&quot;Danish&quot;/&gt;
        ///  &lt;/xfd:localization&gt;
        ///  
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Xena_Reports_DefaultXSLT_OrderDelivery {
            get {
                return ResourceManager.GetString("Xena_Reports_DefaultXSLT_OrderDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xfd:document xmlns:xfd=&quot;http://www.ecrion.com/xfd/1.0&quot; xmlns:fo=&quot;http://www.w3.org/1999/XSL/Format&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:xf=&quot;http://www.ecrion.com/xf/1.0&quot; xmlns:xc=&quot;http://www.ecrion.com/2008/xc&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot; dt-namespaces=&quot;&quot; sample-xml=&quot;.\ExampleData\Xena_Reports_DefaultXSLT_OrderInvoice.xml&quot;&gt;
        ///	&lt;xfd:localization&gt;
        ///		&lt;xfd:locale language-id=&quot;da_DK&quot; language-name=&quot;Danish&quot;/&gt;
        ///	&lt;/xfd:localization&gt;
        ///&lt;!-- Attrib [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Xena_Reports_DefaultXSLT_OrderInvoice {
            get {
                return ResourceManager.GetString("Xena_Reports_DefaultXSLT_OrderInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;xfd:document xmlns:xfd=&quot;http://www.ecrion.com/xfd/1.0&quot; xmlns:fo=&quot;http://www.w3.org/1999/XSL/Format&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:xf=&quot;http://www.ecrion.com/xf/1.0&quot; xmlns:xc=&quot;http://www.ecrion.com/2008/xc&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot; dt-namespaces=&quot;&quot; sample-xml=&quot;.\ExampleData\Xena_Reports_DefaultXSLT_OrderOffer.xml&quot;&gt;
        ///  &lt;xfd:localization&gt;
        ///    &lt;xfd:locale language-id=&quot;da_DK&quot; language-name=&quot;Danish&quot;/&gt;
        ///  &lt;/xfd:localization&gt;
        ///  
        ///  &lt;! [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Xena_Reports_DefaultXSLT_OrderOffer {
            get {
                return ResourceManager.GetString("Xena_Reports_DefaultXSLT_OrderOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;xfd:document xmlns:xfd=&quot;http://www.ecrion.com/xfd/1.0&quot; xmlns:fo=&quot;http://www.w3.org/1999/XSL/Format&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:xf=&quot;http://www.ecrion.com/xf/1.0&quot; xmlns:xc=&quot;http://www.ecrion.com/2008/xc&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot; dt-namespaces=&quot;&quot; sample-xml=&quot;.\ExampleData\Xena_Reports_DefaultXSLT_OrderPickList.xml&quot;&gt;
        ///  &lt;xfd:localization&gt;
        ///    &lt;xfd:locale language-id=&quot;da_DK&quot; language-name=&quot;Danish&quot;/&gt;
        ///  &lt;/xfd:localization&gt;
        ///  
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Xena_Reports_DefaultXSLT_OrderPickList {
            get {
                return ResourceManager.GetString("Xena_Reports_DefaultXSLT_OrderPickList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xfd:document xmlns:fo=&quot;http://www.w3.org/1999/XSL/Format&quot; xmlns:xfd=&quot;http://www.ecrion.com/xfd/1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:xf=&quot;http://www.ecrion.com/xf/1.0&quot; xmlns:xc=&quot;http://www.ecrion.com/2008/xc&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot; fo:font-family=&quot;Times&quot; fo:font-size=&quot;12pt&quot; sample-xml=&quot;.\ExampleData\Xena_Reports_DefaultXSLT_PartnerBalance.xml&quot;&gt;
        ///  &lt;xfd:localization&gt;
        ///    &lt;xfd:locale language-id=&quot;da_DK&quot; language-name=&quot;Danish&quot;/&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Xena_Reports_DefaultXSLT_PartnerBalance {
            get {
                return ResourceManager.GetString("Xena_Reports_DefaultXSLT_PartnerBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xfd:document xmlns:fo=&quot;http://www.w3.org/1999/XSL/Format&quot; xmlns:xfd=&quot;http://www.ecrion.com/xfd/1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:xf=&quot;http://www.ecrion.com/xf/1.0&quot; xmlns:xc=&quot;http://www.ecrion.com/2008/xc&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot; fo:font-family=&quot;Times&quot; fo:font-size=&quot;12pt&quot; sample-xml=&quot;.\ExampleData\Xena_Reports_DefaultXSLT_PartnerPostReportList.xml&quot;&gt;
        ///  &lt;xfd:localization&gt;
        ///    &lt;xfd:locale language-id=&quot;da_DK&quot; language-name=&quot;Danish [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Xena_Reports_DefaultXSLT_PartnerPostReportList {
            get {
                return ResourceManager.GetString("Xena_Reports_DefaultXSLT_PartnerPostReportList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xfd:document xmlns:fo=&quot;http://www.w3.org/1999/XSL/Format&quot; xmlns:xfd=&quot;http://www.ecrion.com/xfd/1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:xf=&quot;http://www.ecrion.com/xf/1.0&quot; xmlns:xc=&quot;http://www.ecrion.com/2008/xc&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot; fo:font-family=&quot;Times&quot; fo:font-size=&quot;12pt&quot; sample-xml=&quot;.\ExampleData\Xena_Reports_DefaultXSLT_PartnerSaldoAgeReportList.xml&quot;&gt;
        ///  &lt;xfd:localization&gt;
        ///    &lt;xfd:locale language-id=&quot;da_DK&quot; language-name=&quot;Da [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Xena_Reports_DefaultXSLT_PartnerSaldoAgeReportList {
            get {
                return ResourceManager.GetString("Xena_Reports_DefaultXSLT_PartnerSaldoAgeReportList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xfd:document xmlns:fo=&quot;http://www.w3.org/1999/XSL/Format&quot; xmlns:xfd=&quot;http://www.ecrion.com/xfd/1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:xf=&quot;http://www.ecrion.com/xf/1.0&quot; xmlns:xc=&quot;http://www.ecrion.com/2008/xc&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot; fo:font-family=&quot;Times&quot; fo:font-size=&quot;12pt&quot; sample-xml=&quot;.\ExampleData\Xena_Reports_DefaultXSLT_PartnerSaldoReportList.xml&quot;&gt;
        ///  &lt;xfd:localization&gt;
        ///    &lt;xfd:locale language-id=&quot;da_DK&quot; language-name=&quot;Danis [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Xena_Reports_DefaultXSLT_PartnerSaldoReportList {
            get {
                return ResourceManager.GetString("Xena_Reports_DefaultXSLT_PartnerSaldoReportList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xfd:document xmlns:fo=&quot;http://www.w3.org/1999/XSL/Format&quot; xmlns:xfd=&quot;http://www.ecrion.com/xfd/1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:xf=&quot;http://www.ecrion.com/xf/1.0&quot; xmlns:xc=&quot;http://www.ecrion.com/2008/xc&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot; fo:font-family=&quot;Times&quot; fo:font-size=&quot;12pt&quot; sample-xml=&quot;.\ExampleData\Xena_Reports_DefaultXSLT_PartnerBalance.xml&quot;&gt;
        ///	&lt;xfd:localization&gt;
        ///		&lt;xfd:locale language-id=&quot;da_DK&quot; language-name=&quot;Danish&quot;/&gt;
        ///	&lt;/xf [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Xena_Reports_DefaultXSLT_PartnerStatisticReportList {
            get {
                return ResourceManager.GetString("Xena_Reports_DefaultXSLT_PartnerStatisticReportList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xfd:document xmlns:fo=&quot;http://www.w3.org/1999/XSL/Format&quot; xmlns:xfd=&quot;http://www.ecrion.com/xfd/1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:xf=&quot;http://www.ecrion.com/xf/1.0&quot; xmlns:xc=&quot;http://www.ecrion.com/2008/xc&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot; fo:font-family=&quot;Times&quot; fo:font-size=&quot;12pt&quot; sample-xml=&quot;.\ExampleData\Xena_Reports_DefaultXSLT_ArticlePostReportList.xml&quot;&gt;
        ///	&lt;xfd:localization&gt;
        ///		&lt;xfd:locale language-id=&quot;da_DK&quot; language-name=&quot;Danish&quot;/&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Xena_Reports_DefaultXSLT_PriceAgreementReportList {
            get {
                return ResourceManager.GetString("Xena_Reports_DefaultXSLT_PriceAgreementReportList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xfd:document xmlns:fo=&quot;http://www.w3.org/1999/XSL/Format&quot; xmlns:xfd=&quot;http://www.ecrion.com/xfd/1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:xf=&quot;http://www.ecrion.com/xf/1.0&quot; xmlns:xc=&quot;http://www.ecrion.com/2008/xc&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot; fo:font-family=&quot;Times&quot; fo:font-size=&quot;12pt&quot; sample-xml=&quot;.\Data\FiscalBalanceExample1.xml&quot;&gt;
        /// &lt;xfd:localization&gt;
        ///  &lt;xfd:locale language-id=&quot;en_US&quot; language-name=&quot;English (United States)&quot;/&gt;
        /// &lt;/xfd:locali [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Xena_Reports_DefaultXSLT_PrimoFiscalBalance {
            get {
                return ResourceManager.GetString("Xena_Reports_DefaultXSLT_PrimoFiscalBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xfd:document xmlns:xfd=&quot;http://www.ecrion.com/xfd/1.0&quot; xmlns:fo=&quot;http://www.w3.org/1999/XSL/Format&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:xf=&quot;http://www.ecrion.com/xf/1.0&quot; xmlns:xc=&quot;http://www.ecrion.com/2008/xc&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot; dt-namespaces=&quot;&quot; sample-xml=&quot;.\ExampleData\Xena_Reports_DefaultXSLT_Reminder.xml&quot;&gt;
        ///	&lt;xfd:localization&gt;
        ///		&lt;xfd:locale language-id=&quot;da_DK&quot; language-name=&quot;Danish&quot;/&gt;
        ///	&lt;/xfd:localization&gt;
        ///&lt;!-- Attributes [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Xena_Reports_DefaultXSLT_Reminder {
            get {
                return ResourceManager.GetString("Xena_Reports_DefaultXSLT_Reminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xfd:document xmlns:fo=&quot;http://www.w3.org/1999/XSL/Format&quot; xmlns:xfd=&quot;http://www.ecrion.com/xfd/1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:xf=&quot;http://www.ecrion.com/xf/1.0&quot; xmlns:xc=&quot;http://www.ecrion.com/2008/xc&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot; fo:font-family=&quot;Times&quot; fo:font-size=&quot;12pt&quot; sample-xml=&quot;.\ExampleData\Xena_Reports_DefaultXSLT_VatSettlement.xml&quot;&gt;
        ///  &lt;xfd:localization&gt;
        ///    &lt;xfd:locale language-id=&quot;da_DK&quot; language-name=&quot;Danish&quot;/&gt;
        ///  &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Xena_Reports_DefaultXSLT_VatSettlement {
            get {
                return ResourceManager.GetString("Xena_Reports_DefaultXSLT_VatSettlement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xfd:document xmlns:fo=&quot;http://www.w3.org/1999/XSL/Format&quot; xmlns:xfd=&quot;http://www.ecrion.com/xfd/1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:xf=&quot;http://www.ecrion.com/xf/1.0&quot; xmlns:xc=&quot;http://www.ecrion.com/2008/xc&quot; xmlns:svg=&quot;http://www.w3.org/2000/svg&quot; fo:font-family=&quot;Times&quot; fo:font-size=&quot;12pt&quot; sample-xml=&quot;.\ExampleData\Xena_Reports_DefaultXSLT_VatSettlement.xml&quot;&gt;
        ///  &lt;xfd:localization&gt;
        ///    &lt;xfd:locale language-id=&quot;da_DK&quot; language-name=&quot;Danish&quot;/&gt;
        ///  &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Xena_Reports_DefaultXSLT_VatSettlement_OneStop {
            get {
                return ResourceManager.GetString("Xena_Reports_DefaultXSLT_VatSettlement_OneStop", resourceCulture);
            }
        }
    }
}
