# configuration for develop branch
# build in Debug mode and deployed to dev slot
- 
  branches:
    only:
      - master

  version: 0.0.{build}
  force_https_clone: true
  os: Visual Studio 2015
  
  configuration: Develop

  build_script:
    - cmd: nuget sources add -Name BetaFeed -Source https://www.myget.org/F/aspnet-contrib/api/v3/index.json
    - cmd: dotnet --info
    - cmd: dotnet restore
    - cmd: dotnet build -c Debug src\Xena.Contracts

  after_test:
    - cmd: dotnet pack -c Debug src\Xena.Contracts

  artifacts:

    - path: src\Xena.Contracts\bin\Debug\*.nupkg
      name: Xena.Contracts.nupkg

  deploy:

    # Deploy NuGet to nuget.org
    - provider: NuGet
      api_key: 086f2040-5566-42ec-857e-2d8753910863
      skip_symbols: false
      artifact: Xena.Contracts.nupkg


# "fall back" configuration for all other branches
# do not build
- 
  build: off