//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xena.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Currencies {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Currencies() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xena.Resources.Currencies", typeof(Currencies).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UAE Dirham.
        /// </summary>
        public static string Localized_Currency_AED {
            get {
                return ResourceManager.GetString("Localized_Currency_AED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afghani.
        /// </summary>
        public static string Localized_Currency_AFN {
            get {
                return ResourceManager.GetString("Localized_Currency_AFN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albanian Lek.
        /// </summary>
        public static string Localized_Currency_ALL {
            get {
                return ResourceManager.GetString("Localized_Currency_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armenian Dram.
        /// </summary>
        public static string Localized_Currency_AMD {
            get {
                return ResourceManager.GetString("Localized_Currency_AMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argentine Peso.
        /// </summary>
        public static string Localized_Currency_ARS {
            get {
                return ResourceManager.GetString("Localized_Currency_ARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Australian Dollar.
        /// </summary>
        public static string Localized_Currency_AUD {
            get {
                return ResourceManager.GetString("Localized_Currency_AUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azerbaijanian Manat.
        /// </summary>
        public static string Localized_Currency_AZN {
            get {
                return ResourceManager.GetString("Localized_Currency_AZN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convertible Marks.
        /// </summary>
        public static string Localized_Currency_BAM {
            get {
                return ResourceManager.GetString("Localized_Currency_BAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bangladeshi Taka.
        /// </summary>
        public static string Localized_Currency_BDT {
            get {
                return ResourceManager.GetString("Localized_Currency_BDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulgarian Lev.
        /// </summary>
        public static string Localized_Currency_BGN {
            get {
                return ResourceManager.GetString("Localized_Currency_BGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bahraini Dinar.
        /// </summary>
        public static string Localized_Currency_BHD {
            get {
                return ResourceManager.GetString("Localized_Currency_BHD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brunei Dollar.
        /// </summary>
        public static string Localized_Currency_BND {
            get {
                return ResourceManager.GetString("Localized_Currency_BND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boliviano.
        /// </summary>
        public static string Localized_Currency_BOB {
            get {
                return ResourceManager.GetString("Localized_Currency_BOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real.
        /// </summary>
        public static string Localized_Currency_BRL {
            get {
                return ResourceManager.GetString("Localized_Currency_BRL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belarusian Ruble.
        /// </summary>
        public static string Localized_Currency_BYR {
            get {
                return ResourceManager.GetString("Localized_Currency_BYR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belize Dollar.
        /// </summary>
        public static string Localized_Currency_BZD {
            get {
                return ResourceManager.GetString("Localized_Currency_BZD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canadian Dollar.
        /// </summary>
        public static string Localized_Currency_CAD {
            get {
                return ResourceManager.GetString("Localized_Currency_CAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swiss Franc.
        /// </summary>
        public static string Localized_Currency_CHF {
            get {
                return ResourceManager.GetString("Localized_Currency_CHF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swiss Franc.
        /// </summary>
        public static string Localized_Currency_CHF1 {
            get {
                return ResourceManager.GetString("Localized_Currency_CHF1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chilean Peso.
        /// </summary>
        public static string Localized_Currency_CLP {
            get {
                return ResourceManager.GetString("Localized_Currency_CLP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRC Renminbi.
        /// </summary>
        public static string Localized_Currency_CNY {
            get {
                return ResourceManager.GetString("Localized_Currency_CNY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colombian Peso.
        /// </summary>
        public static string Localized_Currency_COP {
            get {
                return ResourceManager.GetString("Localized_Currency_COP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costa Rican Colon.
        /// </summary>
        public static string Localized_Currency_CRC {
            get {
                return ResourceManager.GetString("Localized_Currency_CRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serbian Dinar.
        /// </summary>
        public static string Localized_Currency_CSD {
            get {
                return ResourceManager.GetString("Localized_Currency_CSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czech Koruna.
        /// </summary>
        public static string Localized_Currency_CZK {
            get {
                return ResourceManager.GetString("Localized_Currency_CZK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danish Krone.
        /// </summary>
        public static string Localized_Currency_DKK {
            get {
                return ResourceManager.GetString("Localized_Currency_DKK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dominican Peso.
        /// </summary>
        public static string Localized_Currency_DOP {
            get {
                return ResourceManager.GetString("Localized_Currency_DOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algerian Dinar.
        /// </summary>
        public static string Localized_Currency_DZD {
            get {
                return ResourceManager.GetString("Localized_Currency_DZD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estonian Kroon.
        /// </summary>
        public static string Localized_Currency_EEK {
            get {
                return ResourceManager.GetString("Localized_Currency_EEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egyptian Pound.
        /// </summary>
        public static string Localized_Currency_EGP {
            get {
                return ResourceManager.GetString("Localized_Currency_EGP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethiopian Birr.
        /// </summary>
        public static string Localized_Currency_ETB {
            get {
                return ResourceManager.GetString("Localized_Currency_ETB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Euro.
        /// </summary>
        public static string Localized_Currency_EUR {
            get {
                return ResourceManager.GetString("Localized_Currency_EUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UK Pound Sterling.
        /// </summary>
        public static string Localized_Currency_GBP {
            get {
                return ResourceManager.GetString("Localized_Currency_GBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lari.
        /// </summary>
        public static string Localized_Currency_GEL {
            get {
                return ResourceManager.GetString("Localized_Currency_GEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guatemalan Quetzal.
        /// </summary>
        public static string Localized_Currency_GTQ {
            get {
                return ResourceManager.GetString("Localized_Currency_GTQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hong Kong Dollar.
        /// </summary>
        public static string Localized_Currency_HKD {
            get {
                return ResourceManager.GetString("Localized_Currency_HKD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honduran Lempira.
        /// </summary>
        public static string Localized_Currency_HNL {
            get {
                return ResourceManager.GetString("Localized_Currency_HNL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croatian Kuna.
        /// </summary>
        public static string Localized_Currency_HRK {
            get {
                return ResourceManager.GetString("Localized_Currency_HRK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hungarian Forint.
        /// </summary>
        public static string Localized_Currency_HUF {
            get {
                return ResourceManager.GetString("Localized_Currency_HUF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indonesian Rupiah.
        /// </summary>
        public static string Localized_Currency_IDR {
            get {
                return ResourceManager.GetString("Localized_Currency_IDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Israeli New Shekel.
        /// </summary>
        public static string Localized_Currency_ILS {
            get {
                return ResourceManager.GetString("Localized_Currency_ILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indian Rupee.
        /// </summary>
        public static string Localized_Currency_INR {
            get {
                return ResourceManager.GetString("Localized_Currency_INR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iraqi Dinar.
        /// </summary>
        public static string Localized_Currency_IQD {
            get {
                return ResourceManager.GetString("Localized_Currency_IQD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iranian Rial.
        /// </summary>
        public static string Localized_Currency_IRR {
            get {
                return ResourceManager.GetString("Localized_Currency_IRR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icelandic Krona.
        /// </summary>
        public static string Localized_Currency_ISK {
            get {
                return ResourceManager.GetString("Localized_Currency_ISK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jamaican Dollar.
        /// </summary>
        public static string Localized_Currency_JMD {
            get {
                return ResourceManager.GetString("Localized_Currency_JMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jordanian Dinar.
        /// </summary>
        public static string Localized_Currency_JOD {
            get {
                return ResourceManager.GetString("Localized_Currency_JOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese Yen.
        /// </summary>
        public static string Localized_Currency_JPY {
            get {
                return ResourceManager.GetString("Localized_Currency_JPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kenyan Shilling.
        /// </summary>
        public static string Localized_Currency_KES {
            get {
                return ResourceManager.GetString("Localized_Currency_KES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Som.
        /// </summary>
        public static string Localized_Currency_KGS {
            get {
                return ResourceManager.GetString("Localized_Currency_KGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riel.
        /// </summary>
        public static string Localized_Currency_KHR {
            get {
                return ResourceManager.GetString("Localized_Currency_KHR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korean Won.
        /// </summary>
        public static string Localized_Currency_KRW {
            get {
                return ResourceManager.GetString("Localized_Currency_KRW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kuwaiti Dinar.
        /// </summary>
        public static string Localized_Currency_KWD {
            get {
                return ResourceManager.GetString("Localized_Currency_KWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenge.
        /// </summary>
        public static string Localized_Currency_KZT {
            get {
                return ResourceManager.GetString("Localized_Currency_KZT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kip.
        /// </summary>
        public static string Localized_Currency_LAK {
            get {
                return ResourceManager.GetString("Localized_Currency_LAK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lebanese Pound.
        /// </summary>
        public static string Localized_Currency_LBP {
            get {
                return ResourceManager.GetString("Localized_Currency_LBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sri Lanka Rupee.
        /// </summary>
        public static string Localized_Currency_LKR {
            get {
                return ResourceManager.GetString("Localized_Currency_LKR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lithuanian Litas.
        /// </summary>
        public static string Localized_Currency_LTL {
            get {
                return ResourceManager.GetString("Localized_Currency_LTL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latvian Lats.
        /// </summary>
        public static string Localized_Currency_LVL {
            get {
                return ResourceManager.GetString("Localized_Currency_LVL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libyan Dinar.
        /// </summary>
        public static string Localized_Currency_LYD {
            get {
                return ResourceManager.GetString("Localized_Currency_LYD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moroccan Dirham.
        /// </summary>
        public static string Localized_Currency_MAD {
            get {
                return ResourceManager.GetString("Localized_Currency_MAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macedonian Denar.
        /// </summary>
        public static string Localized_Currency_MKD {
            get {
                return ResourceManager.GetString("Localized_Currency_MKD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tugrik.
        /// </summary>
        public static string Localized_Currency_MNT {
            get {
                return ResourceManager.GetString("Localized_Currency_MNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macao Pataca.
        /// </summary>
        public static string Localized_Currency_MOP {
            get {
                return ResourceManager.GetString("Localized_Currency_MOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rufiyaa.
        /// </summary>
        public static string Localized_Currency_MVR {
            get {
                return ResourceManager.GetString("Localized_Currency_MVR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mexican Peso.
        /// </summary>
        public static string Localized_Currency_MXN {
            get {
                return ResourceManager.GetString("Localized_Currency_MXN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malaysian Ringgit.
        /// </summary>
        public static string Localized_Currency_MYR {
            get {
                return ResourceManager.GetString("Localized_Currency_MYR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nigerian Naira.
        /// </summary>
        public static string Localized_Currency_NIO {
            get {
                return ResourceManager.GetString("Localized_Currency_NIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicaraguan Cordoba Oro.
        /// </summary>
        public static string Localized_Currency_NIO1 {
            get {
                return ResourceManager.GetString("Localized_Currency_NIO1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norwegian Krone.
        /// </summary>
        public static string Localized_Currency_NOK {
            get {
                return ResourceManager.GetString("Localized_Currency_NOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepalese Rupees.
        /// </summary>
        public static string Localized_Currency_NPR {
            get {
                return ResourceManager.GetString("Localized_Currency_NPR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Zealand Dollar.
        /// </summary>
        public static string Localized_Currency_NZD {
            get {
                return ResourceManager.GetString("Localized_Currency_NZD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omani Rial.
        /// </summary>
        public static string Localized_Currency_OMR {
            get {
                return ResourceManager.GetString("Localized_Currency_OMR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panamanian Balboa.
        /// </summary>
        public static string Localized_Currency_PAB {
            get {
                return ResourceManager.GetString("Localized_Currency_PAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peruvian Nuevo Sol.
        /// </summary>
        public static string Localized_Currency_PEN {
            get {
                return ResourceManager.GetString("Localized_Currency_PEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Philippine Peso.
        /// </summary>
        public static string Localized_Currency_PHP {
            get {
                return ResourceManager.GetString("Localized_Currency_PHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pakistan Rupee.
        /// </summary>
        public static string Localized_Currency_PKR {
            get {
                return ResourceManager.GetString("Localized_Currency_PKR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish Zloty.
        /// </summary>
        public static string Localized_Currency_PLN {
            get {
                return ResourceManager.GetString("Localized_Currency_PLN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paraguay Guarani.
        /// </summary>
        public static string Localized_Currency_PYG {
            get {
                return ResourceManager.GetString("Localized_Currency_PYG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qatari Rial.
        /// </summary>
        public static string Localized_Currency_QAR {
            get {
                return ResourceManager.GetString("Localized_Currency_QAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romanian Leu.
        /// </summary>
        public static string Localized_Currency_RON {
            get {
                return ResourceManager.GetString("Localized_Currency_RON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serbian Dinar.
        /// </summary>
        public static string Localized_Currency_RSD {
            get {
                return ResourceManager.GetString("Localized_Currency_RSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian Ruble.
        /// </summary>
        public static string Localized_Currency_RUB {
            get {
                return ResourceManager.GetString("Localized_Currency_RUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rwandan Franc.
        /// </summary>
        public static string Localized_Currency_RWF {
            get {
                return ResourceManager.GetString("Localized_Currency_RWF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saudi Riyal.
        /// </summary>
        public static string Localized_Currency_SAR {
            get {
                return ResourceManager.GetString("Localized_Currency_SAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swedish Krona.
        /// </summary>
        public static string Localized_Currency_SEK {
            get {
                return ResourceManager.GetString("Localized_Currency_SEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singapore Dollar.
        /// </summary>
        public static string Localized_Currency_SGD {
            get {
                return ResourceManager.GetString("Localized_Currency_SGD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syrian Pound.
        /// </summary>
        public static string Localized_Currency_SYP {
            get {
                return ResourceManager.GetString("Localized_Currency_SYP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thai Baht.
        /// </summary>
        public static string Localized_Currency_THB {
            get {
                return ResourceManager.GetString("Localized_Currency_THB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruble.
        /// </summary>
        public static string Localized_Currency_TJS {
            get {
                return ResourceManager.GetString("Localized_Currency_TJS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkmen manat.
        /// </summary>
        public static string Localized_Currency_TMT {
            get {
                return ResourceManager.GetString("Localized_Currency_TMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tunisian Dinar.
        /// </summary>
        public static string Localized_Currency_TND {
            get {
                return ResourceManager.GetString("Localized_Currency_TND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkish Lira.
        /// </summary>
        public static string Localized_Currency_TRY {
            get {
                return ResourceManager.GetString("Localized_Currency_TRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trinidad Dollar.
        /// </summary>
        public static string Localized_Currency_TTD {
            get {
                return ResourceManager.GetString("Localized_Currency_TTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Taiwan Dollar.
        /// </summary>
        public static string Localized_Currency_TWD {
            get {
                return ResourceManager.GetString("Localized_Currency_TWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukrainian Grivna.
        /// </summary>
        public static string Localized_Currency_UAH {
            get {
                return ResourceManager.GetString("Localized_Currency_UAH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Dollar.
        /// </summary>
        public static string Localized_Currency_USD {
            get {
                return ResourceManager.GetString("Localized_Currency_USD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peso Uruguayo.
        /// </summary>
        public static string Localized_Currency_UYU {
            get {
                return ResourceManager.GetString("Localized_Currency_UYU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzbekistan Som.
        /// </summary>
        public static string Localized_Currency_UZS {
            get {
                return ResourceManager.GetString("Localized_Currency_UZS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venezuelan Bolivar.
        /// </summary>
        public static string Localized_Currency_VEF {
            get {
                return ResourceManager.GetString("Localized_Currency_VEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vietnamese Dong.
        /// </summary>
        public static string Localized_Currency_VND {
            get {
                return ResourceManager.GetString("Localized_Currency_VND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XOF Senegal.
        /// </summary>
        public static string Localized_Currency_XOF {
            get {
                return ResourceManager.GetString("Localized_Currency_XOF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yemeni Rial.
        /// </summary>
        public static string Localized_Currency_YER {
            get {
                return ResourceManager.GetString("Localized_Currency_YER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South African Rand.
        /// </summary>
        public static string Localized_Currency_ZAR {
            get {
                return ResourceManager.GetString("Localized_Currency_ZAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zimbabwe Dollar.
        /// </summary>
        public static string Localized_Currency_ZWL {
            get {
                return ResourceManager.GetString("Localized_Currency_ZWL", resourceCulture);
            }
        }
    }
}
