//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xena.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DummyData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DummyData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xena.Resources.DummyData", typeof(DummyData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounting.
        /// </summary>
        public static string DummyData_Accounting {
            get {
                return ResourceManager.GetString("DummyData_Accounting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accountant, Set aside .
        /// </summary>
        public static string DummyData_Accounting_SetAside {
            get {
                return ResourceManager.GetString("DummyData_Accounting_SetAside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accountant, special assignment.
        /// </summary>
        public static string DummyData_Accounting_SpecialAssignment {
            get {
                return ResourceManager.GetString("DummyData_Accounting_SpecialAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accrual.
        /// </summary>
        public static string DummyData_Accrual {
            get {
                return ResourceManager.GetString("DummyData_Accrual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertising.
        /// </summary>
        public static string DummyData_Advertising {
            get {
                return ResourceManager.GetString("DummyData_Advertising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article description 1.
        /// </summary>
        public static string DummyData_Article_First_Description {
            get {
                return ResourceManager.GetString("DummyData_Article_First_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article description 2.
        /// </summary>
        public static string DummyData_Article_Second_Description {
            get {
                return ResourceManager.GetString("DummyData_Article_Second_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolts.
        /// </summary>
        public static string DummyData_Article_Stock_Descríption {
            get {
                return ResourceManager.GetString("DummyData_Article_Stock_Descríption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B2k.
        /// </summary>
        public static string DummyData_Article_Stock_Number {
            get {
                return ResourceManager.GetString("DummyData_Article_Stock_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sweatshirt.
        /// </summary>
        public static string DummyData_Article_SweatShirt_Descríption {
            get {
                return ResourceManager.GetString("DummyData_Article_SweatShirt_Descríption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T38009-37.
        /// </summary>
        public static string DummyData_Article_SweatShirt_Number {
            get {
                return ResourceManager.GetString("DummyData_Article_SweatShirt_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bucket set.
        /// </summary>
        public static string DummyData_Article_Third_Description {
            get {
                return ResourceManager.GetString("DummyData_Article_Third_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article group {0}.
        /// </summary>
        public static string DummyData_ArticleGroup_Description {
            get {
                return ResourceManager.GetString("DummyData_ArticleGroup_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First article group.
        /// </summary>
        public static string DummyData_ArticleGroup_Description_First {
            get {
                return ResourceManager.GetString("DummyData_ArticleGroup_Description_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second article group.
        /// </summary>
        public static string DummyData_ArticleGroup_Description_Second {
            get {
                return ResourceManager.GetString("DummyData_ArticleGroup_Description_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank.
        /// </summary>
        public static string DummyData_Bank {
            get {
                return ResourceManager.GetString("DummyData_Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank debt.
        /// </summary>
        public static string DummyData_BankDebt {
            get {
                return ResourceManager.GetString("DummyData_BankDebt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank account #1.
        /// </summary>
        public static string DummyData_BankDebt_First {
            get {
                return ResourceManager.GetString("DummyData_BankDebt_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank account #2.
        /// </summary>
        public static string DummyData_BankDebt_Second {
            get {
                return ResourceManager.GetString("DummyData_BankDebt_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonds.
        /// </summary>
        public static string DummyData_Bonds {
            get {
                return ResourceManager.GetString("DummyData_Bonds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brochures.
        /// </summary>
        public static string DummyData_Brochures {
            get {
                return ResourceManager.GetString("DummyData_Brochures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cars.
        /// </summary>
        public static string DummyData_Cars {
            get {
                return ResourceManager.GetString("DummyData_Cars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration dept..
        /// </summary>
        public static string DummyData_Department_Administration {
            get {
                return ResourceManager.GetString("DummyData_Department_Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depreciation.
        /// </summary>
        public static string DummyData_Depreciation {
            get {
                return ResourceManager.GetString("DummyData_Depreciation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electricity.
        /// </summary>
        public static string DummyData_Electricity {
            get {
                return ResourceManager.GetString("DummyData_Electricity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electricity tax.
        /// </summary>
        public static string DummyData_Electricity_Tax {
            get {
                return ResourceManager.GetString("DummyData_Electricity_Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string DummyData_Employees {
            get {
                return ResourceManager.GetString("DummyData_Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goodwill.
        /// </summary>
        public static string DummyData_Goodwill {
            get {
                return ResourceManager.GetString("DummyData_Goodwill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware.
        /// </summary>
        public static string DummyData_Hardware {
            get {
                return ResourceManager.GetString("DummyData_Hardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heating.
        /// </summary>
        public static string DummyData_Heating {
            get {
                return ResourceManager.GetString("DummyData_Heating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lawyers.
        /// </summary>
        public static string DummyData_Lawyers {
            get {
                return ResourceManager.GetString("DummyData_Lawyers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounting.
        /// </summary>
        public static string DummyData_LedgerTag_Accounting {
            get {
                return ResourceManager.GetString("DummyData_LedgerTag_Accounting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S1.
        /// </summary>
        public static string DummyData_Location_Description {
            get {
                return ResourceManager.GetString("DummyData_Location_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shelf #1.
        /// </summary>
        public static string DummyData_Location_Dimension1 {
            get {
                return ResourceManager.GetString("DummyData_Location_Dimension1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk.
        /// </summary>
        public static string DummyData_Location_Dimension1_Bulk {
            get {
                return ResourceManager.GetString("DummyData_Location_Dimension1_Bulk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hall 1.
        /// </summary>
        public static string DummyData_Location_Dimension1_Hall1 {
            get {
                return ResourceManager.GetString("DummyData_Location_Dimension1_Hall1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row 1.
        /// </summary>
        public static string DummyData_Location_Dimension1_Row1 {
            get {
                return ResourceManager.GetString("DummyData_Location_Dimension1_Row1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row 8.
        /// </summary>
        public static string DummyData_Location_Dimension1_Row8 {
            get {
                return ResourceManager.GetString("DummyData_Location_Dimension1_Row8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section 2.
        /// </summary>
        public static string DummyData_Location_Dimension1_Section2 {
            get {
                return ResourceManager.GetString("DummyData_Location_Dimension1_Section2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section 3.
        /// </summary>
        public static string DummyData_Location_Dimension1_Section3 {
            get {
                return ResourceManager.GetString("DummyData_Location_Dimension1_Section3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shelf 1.
        /// </summary>
        public static string DummyData_Location_Dimension1_Shelf1 {
            get {
                return ResourceManager.GetString("DummyData_Location_Dimension1_Shelf1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shelf 3.
        /// </summary>
        public static string DummyData_Location_Dimension1_Shelf3 {
            get {
                return ResourceManager.GetString("DummyData_Location_Dimension1_Shelf3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machinery.
        /// </summary>
        public static string DummyData_Machinery {
            get {
                return ResourceManager.GetString("DummyData_Machinery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual consumption.
        /// </summary>
        public static string DummyData_Manual_Consumption {
            get {
                return ResourceManager.GetString("DummyData_Manual_Consumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual sales.
        /// </summary>
        public static string DummyData_Manual_Sales {
            get {
                return ResourceManager.GetString("DummyData_Manual_Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing costs.
        /// </summary>
        public static string DummyData_Marketing {
            get {
                return ResourceManager.GetString("DummyData_Marketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc. sales costs.
        /// </summary>
        public static string DummyData_MiscSalesCosts {
            get {
                return ResourceManager.GetString("DummyData_MiscSalesCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occasional VAT.
        /// </summary>
        public static string DummyData_OccasionalVAT {
            get {
                return ResourceManager.GetString("DummyData_OccasionalVAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office supplies.
        /// </summary>
        public static string DummyData_OfficeSupplies {
            get {
                return ResourceManager.GetString("DummyData_OfficeSupplies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aalborg.
        /// </summary>
        public static string DummyData_Order_DeliveryAddress_City {
            get {
                return ResourceManager.GetString("DummyData_Order_DeliveryAddress_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery plant # 2.
        /// </summary>
        public static string DummyData_Order_DeliveryAddress_Name {
            get {
                return ResourceManager.GetString("DummyData_Order_DeliveryAddress_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery place.
        /// </summary>
        public static string DummyData_Order_DeliveryAddress_PlaceName {
            get {
                return ResourceManager.GetString("DummyData_Order_DeliveryAddress_PlaceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery street 23.
        /// </summary>
        public static string DummyData_Order_DeliveryAddress_Street {
            get {
                return ResourceManager.GetString("DummyData_Order_DeliveryAddress_Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DK-9000.
        /// </summary>
        public static string DummyData_Order_DeliveryAddress_Zip {
            get {
                return ResourceManager.GetString("DummyData_Order_DeliveryAddress_Zip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invoice@test.com.
        /// </summary>
        public static string DummyData_Order_InvoiceEmail {
            get {
                return ResourceManager.GetString("DummyData_Order_InvoiceEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 342234 (our reference).
        /// </summary>
        public static string DummyData_Order_OurReference {
            get {
                return ResourceManager.GetString("DummyData_Order_OurReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6654-FA (your reference).
        /// </summary>
        public static string DummyData_Order_YourReference {
            get {
                return ResourceManager.GetString("DummyData_Order_YourReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First order task description.
        /// </summary>
        public static string DummyData_OrderTask_First_Description {
            get {
                return ResourceManager.GetString("DummyData_OrderTask_First_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First order task details
        ///First order task - second line details.
        /// </summary>
        public static string DummyData_OrderTask_First_Details {
            get {
                return ResourceManager.GetString("DummyData_OrderTask_First_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second order task description.
        /// </summary>
        public static string DummyData_OrderTask_Second_Description {
            get {
                return ResourceManager.GetString("DummyData_OrderTask_Second_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First order task details
        ///First order task - second line details.
        /// </summary>
        public static string DummyData_OrderTask_Second_Details {
            get {
                return ResourceManager.GetString("DummyData_OrderTask_Second_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The person in charge.
        /// </summary>
        public static string DummyData_Partner_Attention {
            get {
                return ResourceManager.GetString("DummyData_Partner_Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Århus C.
        /// </summary>
        public static string DummyData_Partner_City {
            get {
                return ResourceManager.GetString("DummyData_Partner_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuperSchnell Ltd..
        /// </summary>
        public static string DummyData_Partner_First {
            get {
                return ResourceManager.GetString("DummyData_Partner_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some private consumer.
        /// </summary>
        public static string DummyData_Partner_Fourth {
            get {
                return ResourceManager.GetString("DummyData_Partner_Fourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuperSchnell A/S.
        /// </summary>
        public static string DummyData_Partner_Name {
            get {
                return ResourceManager.GetString("DummyData_Partner_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner note.
        /// </summary>
        public static string DummyData_Partner_Note {
            get {
                return ResourceManager.GetString("DummyData_Partner_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DK-12345678.
        /// </summary>
        public static string DummyData_Partner_OrgNumber {
            get {
                return ResourceManager.GetString("DummyData_Partner_OrgNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main phone.
        /// </summary>
        public static string DummyData_Partner_PhoneNumber {
            get {
                return ResourceManager.GetString("DummyData_Partner_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoicing place name.
        /// </summary>
        public static string DummyData_Partner_PlaceName {
            get {
                return ResourceManager.GetString("DummyData_Partner_PlaceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A company Ltd..
        /// </summary>
        public static string DummyData_Partner_Second {
            get {
                return ResourceManager.GetString("DummyData_Partner_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoicing street 14.
        /// </summary>
        public static string DummyData_Partner_Street {
            get {
                return ResourceManager.GetString("DummyData_Partner_Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mom and Pop&apos;s store.
        /// </summary>
        public static string DummyData_Partner_Third {
            get {
                return ResourceManager.GetString("DummyData_Partner_Third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://xena.biz.
        /// </summary>
        public static string DummyData_Partner_URL {
            get {
                return ResourceManager.GetString("DummyData_Partner_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DK-8000.
        /// </summary>
        public static string DummyData_Partner_Zip {
            get {
                return ResourceManager.GetString("DummyData_Partner_Zip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pensions.
        /// </summary>
        public static string DummyData_Pensions {
            get {
                return ResourceManager.GetString("DummyData_Pensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder step 1.
        /// </summary>
        public static string DummyData_ReminderStep_Description {
            get {
                return ResourceManager.GetString("DummyData_ReminderStep_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent.
        /// </summary>
        public static string DummyData_Rent {
            get {
                return ResourceManager.GetString("DummyData_Rent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rented officeequipment.
        /// </summary>
        public static string DummyData_Rented_Officeequipment {
            get {
                return ResourceManager.GetString("DummyData_Rented_Officeequipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppliers.
        /// </summary>
        public static string DummyData_Rented_Suppliers {
            get {
                return ResourceManager.GetString("DummyData_Rented_Suppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Representation.
        /// </summary>
        public static string DummyData_Representation {
            get {
                return ResourceManager.GetString("DummyData_Representation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pensions.
        /// </summary>
        public static string DummyData_ShortDebt_Pensions {
            get {
                return ResourceManager.GetString("DummyData_ShortDebt_Pensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxes.
        /// </summary>
        public static string DummyData_ShortDebt_Taxes {
            get {
                return ResourceManager.GetString("DummyData_ShortDebt_Taxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stamps.
        /// </summary>
        public static string DummyData_Stamps {
            get {
                return ResourceManager.GetString("DummyData_Stamps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stocks.
        /// </summary>
        public static string DummyData_Stocks {
            get {
                return ResourceManager.GetString("DummyData_Stocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        public static string DummyData_Telephone {
            get {
                return ResourceManager.GetString("DummyData_Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pcs.
        /// </summary>
        public static string DummyData_Unit_Pcs_Abbreviation {
            get {
                return ResourceManager.GetString("DummyData_Unit_Pcs_Abbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pieces.
        /// </summary>
        public static string DummyData_Unit_Pcs_Description {
            get {
                return ResourceManager.GetString("DummyData_Unit_Pcs_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.
        /// </summary>
        public static string DummyData_Unit_Ton_Abbreviation {
            get {
                return ResourceManager.GetString("DummyData_Unit_Ton_Abbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tonnes.
        /// </summary>
        public static string DummyData_Unit_Ton_Description {
            get {
                return ResourceManager.GetString("DummyData_Unit_Ton_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large.
        /// </summary>
        public static string DummyData_Variant_Large {
            get {
                return ResourceManager.GetString("DummyData_Variant_Large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string DummyData_Variant_Medium {
            get {
                return ResourceManager.GetString("DummyData_Variant_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small.
        /// </summary>
        public static string DummyData_Variant_Small {
            get {
                return ResourceManager.GetString("DummyData_Variant_Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I25.
        /// </summary>
        public static string DummyData_Vat_Ingoing_Abbreviation {
            get {
                return ResourceManager.GetString("DummyData_Vat_Ingoing_Abbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingoing VAT.
        /// </summary>
        public static string DummyData_Vat_Ingoing_Description {
            get {
                return ResourceManager.GetString("DummyData_Vat_Ingoing_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual VAT.
        /// </summary>
        public static string DummyData_VAT_Manual {
            get {
                return ResourceManager.GetString("DummyData_VAT_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vat outgoing.
        /// </summary>
        public static string DummyData_Vat_Outgoing_Description {
            get {
                return ResourceManager.GetString("DummyData_Vat_Outgoing_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xena Ltd..
        /// </summary>
        public static string DummyData_VatSpecification_Company {
            get {
                return ResourceManager.GetString("DummyData_VatSpecification_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher description.
        /// </summary>
        public static string DummyData_Voucher_Description {
            get {
                return ResourceManager.GetString("DummyData_Voucher_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wages.
        /// </summary>
        public static string DummyData_Wages {
            get {
                return ResourceManager.GetString("DummyData_Wages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory location #1.
        /// </summary>
        public static string DummyData_Warehouse_Description {
            get {
                return ResourceManager.GetString("DummyData_Warehouse_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row.
        /// </summary>
        public static string DummyData_Warehouse_Dimension1 {
            get {
                return ResourceManager.GetString("DummyData_Warehouse_Dimension1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shelf.
        /// </summary>
        public static string DummyData_Warehouse_Dimension2 {
            get {
                return ResourceManager.GetString("DummyData_Warehouse_Dimension2", resourceCulture);
            }
        }
    }
}
